/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VariableBudgetRouteImport } from './routes/variable-budget'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as FixedExpensesRouteImport } from './routes/fixed-expenses'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as IndexRouteImport } from './routes/index'

const VariableBudgetRoute = VariableBudgetRouteImport.update({
  id: '/variable-budget',
  path: '/variable-budget',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const FixedExpensesRoute = FixedExpensesRouteImport.update({
  id: '/fixed-expenses',
  path: '/fixed-expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/fixed-expenses': typeof FixedExpensesRoute
  '/reports': typeof ReportsRoute
  '/transactions': typeof TransactionsRoute
  '/variable-budget': typeof VariableBudgetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/fixed-expenses': typeof FixedExpensesRoute
  '/reports': typeof ReportsRoute
  '/transactions': typeof TransactionsRoute
  '/variable-budget': typeof VariableBudgetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/fixed-expenses': typeof FixedExpensesRoute
  '/reports': typeof ReportsRoute
  '/transactions': typeof TransactionsRoute
  '/variable-budget': typeof VariableBudgetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/fixed-expenses'
    | '/reports'
    | '/transactions'
    | '/variable-budget'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/fixed-expenses'
    | '/reports'
    | '/transactions'
    | '/variable-budget'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/fixed-expenses'
    | '/reports'
    | '/transactions'
    | '/variable-budget'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRoute: typeof CategoriesRoute
  FixedExpensesRoute: typeof FixedExpensesRoute
  ReportsRoute: typeof ReportsRoute
  TransactionsRoute: typeof TransactionsRoute
  VariableBudgetRoute: typeof VariableBudgetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/variable-budget': {
      id: '/variable-budget'
      path: '/variable-budget'
      fullPath: '/variable-budget'
      preLoaderRoute: typeof VariableBudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixed-expenses': {
      id: '/fixed-expenses'
      path: '/fixed-expenses'
      fullPath: '/fixed-expenses'
      preLoaderRoute: typeof FixedExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRoute,
  FixedExpensesRoute: FixedExpensesRoute,
  ReportsRoute: ReportsRoute,
  TransactionsRoute: TransactionsRoute,
  VariableBudgetRoute: VariableBudgetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
